name: Release

on:
  push:
    branches:
      - main
      - hotfix**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  package-version:
    name: Get Package Version
    runs-on: ubuntu-latest
    container: rust/1.53.0-slim
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            $CARGO_HOME/bin/
            $CARGO_HOME/registry/index/
            $CARGO_HOME/registry/cache/
            $CARGO_HOME/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get package version
        id: get-version
        run: |
          echo ::set-output name=version::$(cargo tree -i wasmvm | grep -oE "[0-9]+(\.[0-9]+){2}-[0-9]+(\.[0-9]+){2}")
  check-version: # check whether the package version exist on git tags
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-check.outputs.git_tag_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: dudo/tag_check@v1.1.1
        id: tag-check
        with:
          version: ${{ needs.package-version.outputs.version }}
          git_tag_prefix: v
  push-tag:
    name: Push Tag
    needs: check_version
    runs-on: ubuntu-latest
    steps:
      - name: Push Tag to GitHub
        run: echo ${{ needs.check-version.outputs.tag }}
